### ISSUE TITLE
Marker: onClick property

### ISSUE THREAD

**Issue by vanroody** [fgnass/googlemaps-react-primitives#1]
This package works so much better than other React Google maps packages that I have tried... 
It is indeed the "missing bits and pieces" from Google's React wrapper. Loving your work!
Any chance of this enhancement to the markers?

**Comment by fgnass** [comment]
Thanks for your feedback, I'm glad you like it! Funnily enough, I have the same requirement in a project right now. I hope to get around to releasing a new version on Monday.

**Comment by vanroody** [comment]
Yes, I really like it. 
I'm using it in project now with a small "patch". Did you see my pull request with this feature? I matched your code formatting and added an example. A first colab from me...!
