### ISSUE TITLE
Module paths not resolved with JavaScript React app using Webpack 5

### ISSUE THREAD

**Issue by vanroody** [fgnass/googlemaps-react-primitives#3]
## Current Behavior

> Compiled with problems:
>
>ERROR in ./src/.../GoogleMapsContainer.js 179:36-45
>export 'GoogleMap' (imported as 'GoogleMap') was not found in 'googlemaps-react-primitives' (module has no exports)
>
>ERROR in ./src/.../GoogleMapsContainer.js 206:39-45
>export 'Marker' (imported as 'Marker') was not found in 'googlemaps-react-primitives' (module has no exports)
>
>ERROR in ./node_modules/googlemaps-react-primitives/lib/index.js 3:0-29
>Module not found: Error: Can't resolve './MapContext' in...

## Possible Solution
`tsconfig.json` or `package.json` need further configuration before building to 'lib' folder, as the module paths are no longer resolved in Webpack 5

## Temporary Solution
Change Webpack config file `/node_modules/webpack/lib/config/defaults.js` 'esm fullySpecified' to 'false'... 
```
 	resolve: {
 		byDependency: {
 			esm: {
-				fullySpecified: true
+				fullySpecified: false
 				}
 			}
		}

```
...and then use more explicit imports... e.g.
```
import { Marker } from 'googlemaps-react-primitives/lib/Marker';
```

## How to Reproduce
Install latest create-react-app... `npx create-react-app@latest [project-name]` (At present this uses webpack@5.72.0)

**Comment by fgnass** [comment]
Should now work in v1.4.1

**Comment by vanroody** [comment]
It does indeed! Simple as that...
Cheers!
