### ISSUE TITLE
React.StrictMode breaks component rendering

### ISSUE THREAD

**Issue by edickins** [fgnass/googlemaps-react-primitives#4]
Hello. I have pulled your repo and it runs as-is fine.

I deployed it in an actual Vite project. I found that the difference between a Vite project and your github example is that Vite wraps an <App/> with <React.StrictMode/> and from what I can see double-rendering that this does is breaking the components displayed on the map - they only appear if you comment them out from App, then uncomment them and HMR renders them.

To test this I removed the <React.StrictMode> wrapper and your map code renders correctly.  If I put the wrapper back it renders the map (and React Developer Tools shows the missing components) but they only render to the map if you comment the Markers out, and then uncomment them and HMR soft-renders the App again.

Some googling suggests the double-render is orphaning components.  I tried to mitigate by fiddling with e.g. Marker useEffect() and useMapEffect() but to to avail. 

hope you can help, thanks, Ed.

**Comment by edickins** [comment]
I have uploaded the vite project to this repository to save time for you

https://github.com/edickins/googlemapsreactprimitives-demo

I put your code from example.tsx into a MyMap that is rendered by App. The MyMap component is inside src>components>googlemaps

# components not rendering
to replicate bug:

- download repo
- run npm install
- run npm run dev to launch app
- notice that the map renders but without markers or overlay
- go to MyMap line 57 and comment out the Markers being rendered
- notice how other map components render through HMR soft re-render
- uncomment the Marker code
- notice the Markers render.
- refresh the page and notice that all map components no-longer render

# render without React.Strictmode
To remove the React.Strict mode go to Main and remove the React.StrictMode wrapper around App
 
- re-run the app (npm run dev)
- Notice that all components render correctly as expected over the map.
- refresh the page and notice components are still rendering correctly.

**Comment by fgnass** [comment]
Thanks for your detailed report. I published a fix as version 1.5.0.
